name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Node.js Cache
      run: npm config get cache

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      run: npx cypress run

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: cypress/videos/
